/**
 * Maps club names to their logo paths in /public/logos/
 * Filenames use lowercase with hyphens
 */

const CLUB_LOGOS: Record<string, string> = {
  // Premier League
  'Arsenal': '/logos/premier-league/arsenal.png',
  'Aston Villa': '/logos/premier-league/aston-villa.png',
  'Bournemouth': '/logos/premier-league/bournemouth.png',
  'Brentford': '/logos/premier-league/brentford.png',
  'Brighton': '/logos/premier-league/brighton.png',
  'Brighton & Hove Albion': '/logos/premier-league/brighton.png',
  'Burnley': '/logos/premier-league/burnley.png',
  'Chelsea': '/logos/premier-league/chelsea.png',
  'Coventry City': '/logos/premier-league/coventry-city.png',
  'Coventry': '/logos/premier-league/coventry-city.png',
  'Crystal Palace': '/logos/premier-league/crystal-palace.png',
  'Palace': '/logos/premier-league/crystal-palace.png',
  'Crystal Palace FC': '/logos/premier-league/crystal-palace.png',
  'CPFC': '/logos/premier-league/crystal-palace.png',
  'Everton': '/logos/premier-league/everton.png',
  'Everton FC': '/logos/premier-league/everton.png',
  'EFC': '/logos/premier-league/everton.png',
  'Fulham': '/logos/premier-league/fulham.png',
  'Hull City': '/logos/premier-league/hull-city.png',
  'Hull': '/logos/premier-league/hull-city.png',
  'Ipswich': '/logos/premier-league/ipswich-town.png',
  'Ipswich Town': '/logos/premier-league/ipswich-town.png',
  'Leeds United': '/logos/premier-league/leeds-united.png',
  'Leeds': '/logos/premier-league/leeds-united.png',
  'Leicester': '/logos/premier-league/leicester-city.png',
  'Leicester City': '/logos/premier-league/leicester-city.png',
  'Liverpool': '/logos/premier-league/liverpool.png',
  'Manchester City': '/logos/premier-league/manchester-city.png',
  'Man City': '/logos/premier-league/manchester-city.png',
  'Manchester United': '/logos/premier-league/manchester-united.png',
  'Manchester Utd': '/logos/premier-league/manchester-united.png',
  'Man United': '/logos/premier-league/manchester-united.png',
  'Newcastle': '/logos/premier-league/newcastle-united.png',
  'Newcastle United': '/logos/premier-league/newcastle-united.png',
  'Norwich City': '/logos/premier-league/norwich-city.png',
  'Norwich': '/logos/premier-league/norwich-city.png',
  'Nottingham': '/logos/premier-league/nottingham-forest.png',
  'Nottingham Forest': '/logos/premier-league/nottingham-forest.png',
  'Forest': '/logos/premier-league/nottingham-forest.png',
  'Southampton': '/logos/premier-league/southampton.png',
  'Sunderland': '/logos/premier-league/sunderland.png',
  'Tottenham': '/logos/premier-league/tottenham-hotspur.png',
  'Tottenham Hotspur': '/logos/premier-league/tottenham-hotspur.png',
  'Spurs': '/logos/premier-league/tottenham-hotspur.png',
  'Watford': '/logos/premier-league/watford.png',
  'West Ham': '/logos/premier-league/west-ham-united.png',
  'West Ham United': '/logos/premier-league/west-ham-united.png',
  'Wolves': '/logos/premier-league/wolves.png',
  'Wolverhampton': '/logos/premier-league/wolves.png',

  // La Liga
  'Atlético Madrid': '/logos/la-liga/atletico-madrid.png',
  'Athletic Bilbao': '/logos/la-liga/athletic.png',
  'Barcelona': '/logos/la-liga/barcelona.png',
  'Cadiz': '/logos/la-liga/cadiz.png',
  'Celta Vigo': '/logos/la-liga/celta.png',
  'Deportivo Alaves': '/logos/la-liga/deportivo-alavez.png',
  'Elche': '/logos/la-liga/elche.png',
  'RCD Espanyol': '/logos/la-liga/espanyol.png',
  'Getafe': '/logos/la-liga/getafe.png',
  'Granada': '/logos/la-liga/granada.png',
  'Levante': '/logos/la-liga/levante.png',
  'Mallorca': '/logos/la-liga/mallorca.png',
  'Osasuna': '/logos/la-liga/osasuna.png',
  'Rayo Vallecano': '/logos/la-liga/rayo-vallecano.png',
  'Real Betis': '/logos/la-liga/real-betis.png',
  'Real Madrid': '/logos/la-liga/real-madrid.png',
  'Real Sociedad': '/logos/la-liga/real-sociedad.png',
  'Sevilla': '/logos/la-liga/sevilla.png',
  'Valencia': '/logos/la-liga/valencia.png',
  'Villarreal': '/logos/la-liga/villarreal.png',

  // Bundesliga
  'Augsburg': '/logos/bundesliga/augsburg.png',
  'FC Augsburg': '/logos/bundesliga/augsburg.png',
  'Bayern Munich': '/logos/bundesliga/bayern.png',
  'FC Bayern': '/logos/bundesliga/bayern.png',
  'Werder Bremen': '/logos/bundesliga/bremen.png',
  'Borussia Dortmund': '/logos/bundesliga/dortmund.png',
  'Dortmund': '/logos/bundesliga/dortmund.png',
  'BVB': '/logos/bundesliga/dortmund.png',
  'Fortuna Dusseldorf': '/logos/bundesliga/dusseldorf.png',
  'Eintracht Frankfurt': '/logos/bundesliga/frankfurt.png',
  'SC Freiburg': '/logos/bundesliga/freiburg.png',
  'Freiburg': '/logos/bundesliga/freiburg.png',
  'SpVgg Greuther Furth': '/logos/bundesliga/furth.png',
  'Hamburg': '/logos/bundesliga/hamburg.png',
  'Hannover 96': '/logos/bundesliga/hannover.png',
  'Hertha BSC Berlin': '/logos/bundesliga/hertha-bsc-berlin.png',
  'TSG Hoffenheim': '/logos/bundesliga/hoffenheim.png',
  'Hoffenheim': '/logos/bundesliga/hoffenheim.png',
  'Bayer Leverkusen': '/logos/bundesliga/leverkusen.png',
  'Leverkusen': '/logos/bundesliga/leverkusen.png',
  '1. FSV Mainz 05': '/logos/bundesliga/mainz.png',
  'Mainz': '/logos/bundesliga/mainz.png',
  'Borussia Mönchengladbach': '/logos/bundesliga/moenchengladbach.png',
  'Monchengladbach': '/logos/bundesliga/moenchengladbach.png',
  '1. FC Nürnberg': '/logos/bundesliga/nuremberg.png',
  'Nuernberg': '/logos/bundesliga/nuremberg.png',
  'RB Leipzig': '/logos/bundesliga/redbull-leipzig.png',
  'Leipzig': '/logos/bundesliga/redbull-leipzig.png',
  'FC Schalke 04': '/logos/bundesliga/schalke.png',
  'Schalke': '/logos/bundesliga/schalke.png',
  'VfB Stuttgart': '/logos/bundesliga/stuttgart.png',
  'Stuttgart': '/logos/bundesliga/stuttgart.png',
  'VfL Wolfsburg': '/logos/bundesliga/wolfsburg.png',
  'Wolfsburg': '/logos/bundesliga/wolfsburg.png',

  // Serie A
  'AC Milan': '/logos/serie-a/ac-milan.png',
  'Milan': '/logos/serie-a/ac-milan.png',
  'Atalanta': '/logos/serie-a/atalanta.png',
  'Bologna': '/logos/serie-a/bologna.png',
  'Cagliari': '/logos/serie-a/cagliari.png',
  'Empoli': '/logos/serie-a/empoli.png',
  'Fiorentina': '/logos/serie-a/fiorentina.png',
  'Genoa': '/logos/serie-a/genoa.png',
  'Hellas Verona': '/logos/serie-a/hellas-verona.png',
  'Verona': '/logos/serie-a/hellas-verona.png',
  'Internazionale': '/logos/serie-a/inter.png',
  'Inter': '/logos/serie-a/inter.png',
  'Juventus': '/logos/serie-a/juventus.png',
  'Lazio': '/logos/serie-a/lazio.png',
  'Napoli': '/logos/serie-a/napoli.png',
  'AS Roma': '/logos/serie-a/roma.png',
  'Roma': '/logos/serie-a/roma.png',
  'Salernitana': '/logos/serie-a/salernitana.png',
  'Sampdoria': '/logos/serie-a/sampdoria.png',
  'Sassuolo': '/logos/serie-a/sassuolo.png',
  'Spezia': '/logos/serie-a/spezia.png',
  'Torino': '/logos/serie-a/torino.png',
  'Udinese': '/logos/serie-a/udinese.png',
  'Venezia': '/logos/serie-a/venezia.png',

  // Ligue 1
  'Angers SCO': '/logos/french-ligue1/angers-sco.png',
  'Angers': '/logos/french-ligue1/angers-sco.png',
  'AS Monaco': '/logos/french-ligue1/as-monaco.png',
  'Monaco': '/logos/french-ligue1/as-monaco.png',
  'AS Saint-Etienne': '/logos/french-ligue1/as-saint-etienne.png',
  'Saint-Etienne': '/logos/french-ligue1/as-saint-etienne.png',
  'Clermont Foot 63': '/logos/french-ligue1/clermont-foot-63.png',
  'Clermont': '/logos/french-ligue1/clermont-foot-63.png',
  'ESTAC Troyes': '/logos/french-ligue1/estac-troyes.png',
  'Troyes': '/logos/french-ligue1/estac-troyes.png',
  'FC Girondins de Bordeaux': '/logos/french-ligue1/fc-girondins-de-bordeaux.png',
  'Bordeaux': '/logos/french-ligue1/fc-girondins-de-bordeaux.png',
  'FC Lorient': '/logos/french-ligue1/fc-lorient.png',
  'Lorient': '/logos/french-ligue1/fc-lorient.png',
  'FC Metz': '/logos/french-ligue1/fc-metz.png',
  'Metz': '/logos/french-ligue1/fc-metz.png',
  'FC Nantes': '/logos/french-ligue1/fc-nantes.png',
  'Nantes': '/logos/french-ligue1/fc-nantes.png',
  'LOSC Lille': '/logos/french-ligue1/losc-lille.png',
  'Lille': '/logos/french-ligue1/losc-lille.png',
  'Montpellier Herault': '/logos/french-ligue1/montpellier-herault.png',
  'Montpellier': '/logos/french-ligue1/montpellier-herault.png',
  'OGC Nice': '/logos/french-ligue1/ogc-nice.png',
  'Nice': '/logos/french-ligue1/ogc-nice.png',
  'Olympique de Marseille': '/logos/french-ligue1/olympique-de-marseille.png',
  'Marseille': '/logos/french-ligue1/olympique-de-marseille.png',
  'Olympique Lyonnais': '/logos/french-ligue1/olympique-lyonnais.png',
  'Lyon': '/logos/french-ligue1/olympique-lyonnais.png',
  'Paris Saint-Germain': '/logos/french-ligue1/paris-saint-germain.png',
  'Paris SG': '/logos/french-ligue1/paris-saint-germain.png',
  'PSG': '/logos/french-ligue1/paris-saint-germain.png',
  'RC Lens': '/logos/french-ligue1/rc-lens.png',
  'Lens': '/logos/french-ligue1/rc-lens.png',
  'RC Strasbourg Alsace': '/logos/french-ligue1/rc-strasbourg-alsace.png',
  'Strasbourg': '/logos/french-ligue1/rc-strasbourg-alsace.png',
  'Stade Brestois 29': '/logos/french-ligue1/stade-brestois-29.png',
  'Brest': '/logos/french-ligue1/stade-brestois-29.png',
  'Stade de Reims': '/logos/french-ligue1/stade-de-reims.png',
  'Reims': '/logos/french-ligue1/stade-de-reims.png',
  'Stade Rennais FC': '/logos/french-ligue1/stade-rennais-fc.png',
  'Rennes': '/logos/french-ligue1/stade-rennais-fc.png',
};

/**
 * Get the logo path for a club
 * @param clubName - The name of the club
 * @returns The path to the logo, or undefined if not found
 */
export function getClubLogo(clubName: string): string | undefined {
  return CLUB_LOGOS[clubName];
}

/**
 * Get the logo path or a placeholder if not found
 * @param clubName - The name of the club
 * @returns The path to the logo, or an empty string if not found
 */
export function getClubLogoWithFallback(clubName: string): string {
  return CLUB_LOGOS[clubName] ?? '';
}
